name: Android CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mobile_app_v2

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Dar permisos a Gradle
        run: chmod +x gradlew

      - name: Compilar APK
        run: ./gradlew assembleDebug
