name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Configurar Android SDK
        uses: android-actions/setup-android@v3

      - name: Instalar NDK y CMake
        run: |
          sdkmanager "ndk;26.1.10909125" "cmake;3.22.1"

      - name: Compilar APK
        working-directory: mobile_app_v2
        run: |
          chmod +x gradlew
          ./gradlew clean
          ./gradlew assembleDebug

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: KorzadiVPN-Debug-APK
          path: mobile_app_v2/app/build/outputs/apk/debug/*.apk
